### ISSUE TITLE
Data-change requests should not be done via GET...

### ISSUE THREAD

**Issue by mcbloch** [ZeusWPI/Haldis#106]
* order close

**Comment by VandorpeDavid** [comment]
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by redfast00** [comment]
Fixed in https://github.com/ZeusWPI/Haldis/commit/5e2d5e659c5b902282747cf9172fa2b408505fac, @VandorpeDavid can you please confirm we are no longer vulnerable?
