### ISSUE TITLE
Fix naming of products

### ISSUE THREAD

**Issue by Zelzahn** [ZeusWPI/Haldis#127]
The following products have a typo in them:

* 't Blauw Kotje: 
    * frikandal XXL
    * sate (should be saté)
* De Fritoloog
   * Frikadel
   * Paard-lookworst
* Pitta Pinte
    * pita pita klein

There's also a lot of products which aren't capitalized.

**Comment by fbegyn** [comment]
> pita pita klein

I suspect that this is not a typo (aside from capitalization). It's probably to differentiate from 'dürum pita klein' and 'pita pita klein'. I also suspect that 'pita kip klein' also exsists.

**Comment by Zelzahn** [comment]
I suspected this, but it seems to me that "Kleine pita" would be a more appropriate name.

**Comment by mcbloch** [comment]
There is a lot of consistency in the naming of products. It's used half half throughout. Sometimes 'klein' in front sometimes behind. I'm not going to change this now cause of the scope but it can be put in a separate issue.
I fixed the other typos.
