### ISSUE TITLE
Remove products which are obviously not real

### ISSUE THREAD

**Issue by Zelzahn** [ZeusWPI/Haldis#128]
E.g. furry porn in the Quick or a Bicky Cheese for €5000 at Olifantje

**Comment by Iepoev** [comment]
furry porn was an actual product though, some kind of childrens apple puree called "funny pom"

**Comment by Iepoev** [comment]
and the price of a bicky cheese was unknown at the time, so 5000 euros is an arbitrary value

**Comment by Iepoev** [comment]
I don't think there are any fake products in the database

**Comment by Robbe7730** [comment]
well, the database does call for some clean-up, remove test locations like Test Please Ignore and an update on the prices.

**Comment by Zelzahn** [comment]
Also according to Google Maps Olifantje is permanently closed.

**Comment by Zelzahn** [comment]
> and the price of a bicky cheese was unknown at the time, so 5000 euros is an arbitrary value

Oh ok, nevermind my issue then.

**Comment by mcbloch** [comment]
For the price unknown see #28

**Comment by mcbloch** [comment]
Not relevant with the change to hlds files.
