### ISSUE TITLE
[PRICING] Blauw kotje 18/06/2019

### ISSUE THREAD

**Issue by fbegyn** [ZeusWPI/Haldis#130]
Certain items on the menu of blauw kotje have changed in price:

* Bamischijf: 1.6 -> 1.8 EUR
* Chixfingers: 3.4 -> 3.5 EUR

An admin should update these in the DB.

**Comment by redfast00** [comment]
Done

**Comment by fbegyn** [comment]
Another set of items need price adjustments:
* Kipcorn: 1.8 -> 2.2
* Frikandel 1.4 -> 1.6
* Oudbrugs kasskrokket: 2 -> 2.1
