### ISSUE TITLE
Add a wildcard field for when making an order from a large store

### ISSUE THREAD

**Issue by Iepoev** [ZeusWPI/Haldis#15]

**Comment by Silox** [comment]
Yes, indeed, this should. This should also trigger a warning that the total price may be incorrect and a question mark next to the persons order.

**Comment by Jan-PieterBaert** [comment]
These days there's a "Vrije keuze" field that's added by default https://github.com/ZeusWPI/Haldis/blob/master/app/hlds/parser.py#L63
