### ISSUE TITLE
Show per order the originating student group

### ISSUE THREAD

**Issue by ajuvercr** [ZeusWPI/Haldis#177]
When multiple student groups create new orders we want to make it obvious what order is for what student group.
When I request pizza, I expect that that pizza comes to the kelder, not the therminal.

Required:
- [x] When creating an order, save originating student group
- [x] Show per open order a picture of the originating student group

Optional:
- [ ] Request from the oauth server to what student group the current user is associated

Maybe more!

**Comment by Jan-PieterBaert** [comment]
Note for the optional: some users might be associated to multiple student groups

**Comment by chvp** [comment]
Is this not already implemented by https://github.com/ZeusWPI/Haldis/pull/193?
