### ISSUE TITLE
Update to python 3.11

### ISSUE THREAD

**Issue by chvp** [ZeusWPI/Haldis#208]

**Comment by chvp** [comment]
There's also a pinned dependency in requirements.in, mentioning that it's incompatible with python >=3.9. Investigate if this can be bumped.

**Comment by maximdeclercq** [comment]
I think Flask should at least be updated to version `2.x.y`  (python 3.10 and 3.11 are tested since [2.0.2](https://github.com/pallets/flask/blob/1f40c77f1d9ad65911eb6716525de6aa302eda4c/src/flask/__init__.py#L46)
