### ISSUE TITLE
Add "not sold anymore" to items

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/Haldis#26]
We can't have the application crashing because an item is deleted when orders are still containing that item. Items should be marked as "not sold anymore" or a better name so the statistics still include their information instead of deleting them.

**Comment by feliciaan** [comment]
We can also remove the location attribute, this causes it to be removed from the list users can choose from.

**Comment by Silox** [comment]
I wouldn’t do that as that also would skew the statistics for that location we might add in the future.


On 2 Apr 2015 at 20:54:52, Feliciaan De Palmenaer (notifications@github.com) wrote:

We can also remove the location attribute, this causes it to be removed from the list users can choose from.

**Comment by redfast00** [comment]
No longer an issue with HLDS
