### ISSUE TITLE
Add more order statuses

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/Haldis#30]
These could be handy:
- [x] open
- [x] closed
- [ ] ordered
- [ ] in transit
- [ ] waiting/queuing
- [ ] on the way back
- [ ] finished

**Comment by mcbloch** [comment]
Is this feasible? All these states need to be followed up by the courier if we want them to be useful.

**Comment by redfast00** [comment]
I don't think couriers would use this
