### ISSUE TITLE
James -> Haldis

### ISSUE THREAD

**Issue by Donvittorio** [ZeusWPI/Haldis#31]
do it

**Comment by feliciaan** [comment]
Please create a pull request.

**Comment by Donvittorio** [comment]
I believe renaming a repository is not possible in a pull request.

Op vr 3 apr. 2015 om 18:30 schreef Feliciaan De Palmenaer <
notifications@github.com>:

**Comment by feliciaan** [comment]
@Donvittorio all references in the code to james should also be changed, and tested.

**Comment by Donvittorio** [comment]
Fixed thanks to #34
