### ISSUE TITLE
Show opening hours 

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/Haldis#56]
So you can now which days the location is open or closed.

**Comment by SirDestrox** [comment]
Also remove the ability to start an order on a day the location is closed.

**Comment by Silox** [comment]
:+1:  I'll even put bounty bounts on this.

**Comment by mcbloch** [comment]
# TODO
* Add textfield for opening hours to model
* Make new migration
* show openinghours in `locations` list
* show openinghours in order for that location, preferable only for the moment the order closes

**Comment by mcbloch** [comment]
Data kan in openstreatmaps ingegeven worden. We linken locaties sowieso al aan een node. 

We kunnen eventueel die data ook opvragen en rechtstreeks weergeven dan.

**Comment by NuttyShrimp** [comment]
This can in a way be linked to #198
