### ISSUE TITLE
Let people fill in special requests

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/Haldis#58]
This is necessary for special requests and because no list is every complete in the application

**Comment by feliciaan** [comment]
So what's the difference with #59?

**Comment by Silox** [comment]
Both are necessary. If I want to order a "Wit broodje met kaas, without mayo with samourai", I want to add "Wit broodje met kaas" to the database if it is not there, and add the "special request"

**Comment by Silox** [comment]
I edited the title to reflect #59
