### ISSUE TITLE
On the fly adding of products in an order

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Haldis#59]

**Comment by feliciaan** [comment]
Duplicate of #58

**Comment by Silox** [comment]
This is not a duplicate; this would add the possibility to make the application more of a user-based effort instead of having to wait for an admin to add stuff to the app.

**Comment by mcbloch** [comment]
With the new system of hlds files this is not possible via the UI. Modifying the hlds files is a piece of cake tho.
