### ISSUE TITLE
Update the logo

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/Haldis#84]
We have a cool logo now, let's use it. Credits to @isasebrechts

![haldis_logo](https://user-images.githubusercontent.com/9478856/29428795-c42e9158-838e-11e7-9ee2-7351ce182736.jpg)

**Comment by Robbe7730** [comment]
The logo is now in `app/static/logo.png`

**Comment by Robbe7730** [comment]
This is fixed in #94
